export type Holiday = {
  month: string;
  name: string;
  dates: string;
  days: number;
  icon: string;
  color: string;
  vibe: string;
  spiritIcon: string;
};

export const HOLIDAYS_2026: Holiday[] = [
  {
    month: "JANUARY",
    name: "New Year Break",
    dates: "Jan 1 - 4",
    days: 4,
    icon: "sparkles",
    color: "#FF9F0A",
    vibe: "FRESH STARTS",
    spiritIcon: "rocket",
  },
  {
    month: "FEBRUARY",
    name: "Union Day",
    dates: "Feb 12 - 13",
    days: 2,
    icon: "people",
    color: "#FF453A",
    vibe: "UNITY & PRIDE",
    spiritIcon: "heart",
  },
  {
    month: "FEBRUARY",
    name: "Chinese New Year",
    dates: "Feb 16 - 17",
    days: 2,
    icon: "moon-outline",
    color: "#FF375F",
    vibe: "LUNAR CELEBRATION",
    spiritIcon: "star",
  },
  {
    month: "MARCH",
    name: "Peasants' Day",
    dates: "Mar 2",
    days: 1,
    icon: "leaf",
    color: "#32D74B",
    vibe: "HARVEST ENERGY",
    spiritIcon: "leaf",
  },
  {
    month: "MARCH",
    name: "Armed Forces' Day",
    dates: "Mar 27",
    days: 1,
    icon: "shield-checkmark",
    color: "#8E8E93",
    vibe: "HONOR & DUTY",
    spiritIcon: "medal",
  },
  {
    month: "APRIL",
    name: "Thingyan Festival",
    dates: "Apr 11 - 19",
    days: 9,
    icon: "water",
    color: "#007AFF",
    vibe: "PURE CELEBRATION",
    spiritIcon: "rainy",
  },
  {
    month: "APRIL",
    name: "Full Moon Kasong",
    dates: "Apr 30",
    days: 1,
    icon: "sunny",
    color: "#FFD60A",
    vibe: "SPIRITUAL LIGHT",
    spiritIcon: "flower",
  },
  {
    month: "MAY",
    name: "Labor Day",
    dates: "May 1",
    days: 1,
    icon: "hammer",
    color: "#FF9F0A",
    vibe: "WORKER'S PRIDE",
    spiritIcon: "construct",
  },
  {
    month: "JULY",
    name: "Martyrs' Day",
    dates: "July 19",
    days: 1,
    icon: "ribbon",
    color: "#FF453A",
    vibe: "REMEMBRANCE",
    spiritIcon: "flag",
  },
  {
    month: "JULY",
    name: "Full Moon Waso",
    dates: "July 29",
    days: 1,
    icon: "book",
    color: "#AF52DE",
    vibe: "BUDDHIST LENT",
    spiritIcon: "infinite",
  },
  {
    month: "OCTOBER",
    name: "Thadingyut",
    dates: "Oct 25 - 27",
    days: 3,
    icon: "flame",
    color: "#FF375F",
    vibe: "LIGHT FESTIVAL",
    spiritIcon: "moon",
  },
  {
    month: "NOVEMBER",
    name: "Tazaungmone",
    dates: "Nov 23 - 24",
    days: 2,
    icon: "balloon",
    color: "#BF5AF2",
    vibe: "BALLOON MAGIC",
    spiritIcon: "star",
  },
  {
    month: "DECEMBER",
    name: "National Day",
    dates: "Dec 4",
    days: 1,
    icon: "flag",
    color: "#007AFF",
    vibe: "NATIONAL UNITY",
    spiritIcon: "people",
  },
  {
    month: "DECEMBER",
    name: "Christmas Day",
    dates: "Dec 25",
    days: 1,
    icon: "gift",
    color: "#FF453A",
    vibe: "JOY & GIVING",
    spiritIcon: "gift",
  },
];
